AllCops:
  TargetRubyVersion: 2.4.1

Metrics/BlockLength:
  Exclude:
   - 'spec/**/*'

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 30

Style/Documentation:
  Enabled: false

Performance/RegexpMatch:
  Exclude:
    - 'Vagrantfile'
