---
dist: trusty
sudo: false
language: ruby

rvm:
  - 2.4.1

before_install:
 - sudo apt-get -qq update
 - sudo apt-get install -y rpm createrepo expect
 - gem install bundler -v 1.16.1

script:
  - bundle exec rubocop
  - bundle exec rake

notifications:
  email:
    on_success: never
    on_failure: never
