---
dist: trusty

language: python
python: 3.5.3
cache: { pip: true, directories: [eggs/] }

install:
  - pip install --upgrade -r requirements.txt
  - buildout

script: bin/test

notifications:
  email:
    on_success: never
    on_failure: never
