---
dist: trusty
sudo: false
language: ruby

ruby: 2.4.1

rvm:
  - 2.4.1

before_install: gem install bundler -v 1.15.4

script:
  - bundle exec 'rubocop'
  - bundle exec rake

notifications:
  email:
    on_success: never
    on_failure: never
