---
- name: build
  hosts: all
  become: true
  roles:
    - role: vagrant-ruby-dev
      ruby_version: 2.4.1
    - role: awscli
  tasks:
    - name: allow ssh env aws
      lineinfile: dest=/etc/ssh/sshd_config line="AcceptEnv AWS_*"
      notify: restart ssh
    - name: install required packages
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - rpm-build
        - cmake
        - createrepo
    - name: install bundler
      become: true
      become_user: vagrant
      command: bash -lc "gem install bundler"
    - name: run bundle install
      become: true
      become_user: vagrant
      command: bash -lc "cd /vagrant/ && bundle install"
  handlers:
    - name: restart ssh
      service: name=sshd state=restarted
