---
- name: build
  hosts: all
  become: true
  roles:
    - role: vagrant-ruby-dev
      ruby_version: 2.4.1
    - role: awscli
  tasks:
    - name: allow ssh env aws
      lineinfile: dest=/etc/ssh/sshd_config line="AcceptEnv AWS_*"
      notify: restart ssh
    - name: install required packages
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - rpm-build
        - rpm-sign
        - cmake
        - createrepo
    - name: install bundler
      become: true
      become_user: vagrant
      command: bash -lc "gem install bundler"
    - name: run bundle install
      become: true
      become_user: vagrant
      command: bash -lc "cd /vagrant/ && bundle install"
    - name: install ~/.rpmmacros
      lineinfile:
        path: "{{ item.path }}"
        create: true
        regexp: '^%_gpg_name'
        line: '%_gpg_name "isre@grindr.com"'
        owner: "{{ item.owner }}"
        group: "{{ item.owner }}"
      with_items:
        - { path: /root/.rpmmacros, owner: root}
        - { path: /home/vagrant/.rpmmacros, owner: vagrant }
  handlers:
    - name: restart ssh
      service: name=sshd state=restarted
