#!/usr/bin/env sh

function remove() {
  local go_root_dir="/usr/lib64/go"

  # unlink link that was made during install
  unlink /usr/local/go

  find "$go_root_dir/bin" -type f -maxdepth 1 | while read script ; do
    # remove symlinks for all go executables
    local script_name="$(basename "$script")"
    update-alternatives --remove ${script_name} ${script}
  done
}

function upgrade() {
  local new_version="$1"
  return 0
}

function main() {
  local action="$1"
  shift

  case $action in
    0)
      remove
      ;;
    1)
      upgrade $@
      ;;
    *)
      ;;
  esac
}

main $@
